# Generated by Django 3.0.5 on 2020-04-08 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('land_id', models.AutoField(primary_key=True, serialize=False)),
                ('longitude', models.CharField(max_length=16)),
                ('latitude', models.CharField(max_length=16)),
                ('size', models.CharField(max_length=16)),
                ('productive_quality', models.CharField(max_length=16)),
                ('land_type', models.CharField(max_length=16)),
                ('quality', models.CharField(max_length=16)),
                ('mineral_quantity', models.CharField(max_length=16)),
                ('road_type', models.CharField(max_length=16)),
                ('distance_to_paved_road', models.CharField(max_length=16)),
                ('distance_to_nearest_town', models.CharField(max_length=16)),
                ('nearest_town_size', models.CharField(max_length=16)),
                ('distance_to_principal_city', models.CharField(max_length=16)),
                ('distance_to_metropolitan_center', models.CharField(max_length=16)),
                ('distance_to_city_towns', models.CharField(max_length=16)),
                ('wheat_allotment', models.CharField(max_length=16)),
                ('cotton_allotment', models.CharField(max_length=16)),
                ('peanut_allotment', models.CharField(max_length=16)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'land',
            },
        ),
    ]
