# Generated by Django 3.0.5 on 2020-04-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='land_value',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='land',
            name='cotton_allotment',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='land',
            name='distance_to_city_towns',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='land',
            name='distance_to_metropolitan_center',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='land',
            name='distance_to_nearest_town',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='land',
            name='distance_to_paved_road',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='land',
            name='distance_to_principal_city',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='land',
            name='land_type',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='land',
            name='latitude',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='land',
            name='longitude',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='land',
            name='mineral_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='land',
            name='nearest_town_size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='land',
            name='peanut_allotment',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='land',
            name='productive_quality',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='land',
            name='quality',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='land',
            name='road_type',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='land',
            name='size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='land',
            name='wheat_allotment',
            field=models.IntegerField(),
        ),
    ]
