# Generated by Django 3.0.5 on 2020-04-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200418_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='latitude',
            field=models.DecimalField(decimal_places=20, max_digits=24),
        ),
        migrations.AlterField(
            model_name='land',
            name='longitude',
            field=models.DecimalField(decimal_places=20, max_digits=24),
        ),
    ]
