# Generated by Django 3.0.5 on 2020-04-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=32)),
                ('house_type', models.CharField(max_length=32)),
                ('price', models.IntegerField(default=0)),
                ('rooms', models.IntegerField(default=0)),
                ('baths', models.IntegerField(default=0)),
                ('area', models.CharField(max_length=32)),
                ('location', models.CharField(max_length=32)),
                ('descrip', models.TextField(blank=True, null=True)),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('photo4', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('video', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=32)),
                ('price', models.IntegerField(default=0)),
                ('area', models.CharField(max_length=32)),
                ('location', models.CharField(max_length=32)),
                ('parcel_no', models.CharField(max_length=32)),
                ('descrip', models.TextField(blank=True, null=True)),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('photo4', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('video', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='photos')),
            ],
        ),
    ]
